import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Load environment variables from .env file if present
try:
    from dotenv import load_dotenv
    # .env is located one directory up from this script (backend/.env)
    env_path = Path(__file__).resolve().parents[1] / ".env"
    load_dotenv(dotenv_path=env_path)
except ImportError:
    # Fallback: manually parse .env file
    env_path = Path(__file__).resolve().parents[2] / ".env"
    if env_path.is_file():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    os.environ.setdefault(key.strip(), val.strip())


# ------------------------------------------------------------
# Configuration - read from environment
# ------------------------------------------------------------
MCP_HOST = os.getenv("MCP_HOST")               # e.g. "mcp.example.com"
MCP_USER = os.getenv("MCP_USER", "ubuntu")
MCP_SSH_KEY = os.getenv("MCP_SSH_KEY")         # path to private key
REMOTE_PROJECT_PATH = os.getenv("REMOTE_PROJECT_PATH")
PLAYWRIGHT_CMD = os.getenv("PLAYWRIGHT_CMD")
REPORT_PATH = os.getenv("MCP_REPORT_PATH", "playwright_report.json")
SLACK_WEBHOOK = os.getenv("SLACK_WEBHOOK")     # optional - where to post a summary


def _require_config() -> None:
    missing = [
        name
        for name, value in {
            "MCP_HOST": MCP_HOST,
            "MCP_USER": MCP_USER,
            "MCP_SSH_KEY": MCP_SSH_KEY,
            "REMOTE_PROJECT_PATH": REMOTE_PROJECT_PATH,
            "PLAYWRIGHT_CMD": PLAYWRIGHT_CMD,
        }.items()
        if not value
    ]
    if missing:
        raise RuntimeError(f"Missing required environment variables: {', '.join(missing)}")


def _ssh_key_path() -> str:
    return str(Path(MCP_SSH_KEY).expanduser())


def _run_ssh_command(command: str) -> str:
    """Execute a command on the remote MCP server via SSH and return stdout."""
    ssh_cmd = [
        "ssh",
        "-i",
        _ssh_key_path(),
        f"{MCP_USER}@{MCP_HOST}",
        command,
    ]
    result = subprocess.run(ssh_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"SSH command failed: {result.stderr.strip()}")
    return result.stdout.strip()


def _trigger_playwright_tests() -> None:
    """Run the configured Playwright command on the MCP server."""
    print("[Orchestrator] Triggering Playwright tests on MCP...")
    _run_ssh_command(f"cd {REMOTE_PROJECT_PATH} && {PLAYWRIGHT_CMD}")


def _fetch_report() -> dict:
    """Download and parse the JSON report generated by Playwright."""
    local_tmp = Path(tempfile.gettempdir()) / "playwright_report.json"
    remote_report_path = REPORT_PATH
    if not remote_report_path.startswith("/"):
        remote_report_path = f"{REMOTE_PROJECT_PATH.rstrip('/')}/{remote_report_path}"

    scp_cmd = [
        "scp",
        "-i",
        _ssh_key_path(),
        f"{MCP_USER}@{MCP_HOST}:{remote_report_path}",
        str(local_tmp),
    ]
    result = subprocess.run(scp_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Failed to fetch report: {result.stderr.strip()}")

    with open(local_tmp, "r", encoding="utf-8") as f:
        return json.load(f)


def _summarize_report(report: dict) -> str:
    """Create a concise human-readable summary from the Playwright JSON report."""
    stats = report.get("stats", {})
    total = stats.get("expected", 0)
    passed = stats.get("passed", 0)
    failed = stats.get("failed", 0)
    flaky = stats.get("flaky", 0)
    return (
        "Playwright Test Summary:\n"
        f"  Total:   {total}\n"
        f"  Passed:  {passed}\n"
        f"  Failed:  {failed}\n"
        f"  Flaky:   {flaky}\n"
    )


def _post_to_slack(message: str) -> None:
    if not SLACK_WEBHOOK:
        print("[Orchestrator] No Slack webhook configured - skipping notification.")
        return

    import urllib.request

    payload = json.dumps({"text": message}).encode("utf-8")
    req = urllib.request.Request(
        SLACK_WEBHOOK,
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as resp:
        if resp.status != 200:
            print(f"[Orchestrator] Slack notification failed: {resp.status}")
        else:
            print("[Orchestrator] Slack notification sent.")


def _check_git_changes() -> bool:
    """Return True if there are no uncommitted changes in the local repo."""
    result = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
    return result.stdout.strip() == ""


def main() -> None:
    try:
        _require_config()
    except RuntimeError as e:
        print(f"[Orchestrator] Configuration error: {e}")
        sys.exit(1)

    if not _check_git_changes():
        print("[Orchestrator] Uncommitted changes detected - aborting test run.")
        sys.exit(1)

    try:
        _trigger_playwright_tests()
    except RuntimeError as e:
        print(f"[Orchestrator] Error during remote test execution: {e}")
        sys.exit(1)

    try:
        report = _fetch_report()
    except RuntimeError as e:
        print(f"[Orchestrator] Error fetching report: {e}")
        sys.exit(1)

    summary = _summarize_report(report)
    print(summary)
    _post_to_slack(summary)


if __name__ == "__main__":
    main()
